name: "NPM CI"
description: "NPM CI"

inputs:
  token:
    description: "GitHub Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: GitHub CLI
      uses: Duncan3142/mono/actions/gh-cli@main
      with:
        token: ${{ inputs.token }}
    - name: Env vars
      uses: Duncan3142/mono/actions/common-env@main
    - name: Volta setup
      uses: Duncan3142/mono/actions/volta@main
    - name: Git scripts
      uses: Duncan3142/mono/tools/git@main
    - name: NPM scripts
      uses: Duncan3142/mono/tools/npm@main
    - name: NPM CI
      shell: bash
      run: |
        set -ueC
        set -o pipefail

        '${{ github.action_path }}/exec.sh'
