name: "GitHub tools"
description: "Install GitHub tools"

runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        set -ueC
        set -o pipefail

        ./install.sh
      working-directory: ${{ github.action_path}}
