name: "Common Env"
description: "Common action env variables"

runs:
  using: "composite"

  steps:
    - name: Environment
      shell: bash
      run: |

        set -ueC
        set -o pipefail

        FORCE_COLOR=3
        GIT_REMOTE=origin

        echo "FORCE_COLOR=$FORCE_COLOR" >> "$GITHUB_ENV"
        echo "GIT_REMOTE=$GIT_REMOTE" >> "$GITHUB_ENV"

        echo "GIT_ACTOR=$GIT_ACTOR" >> "$GITHUB_ENV"
        echo "GIT_SERVER_URL=$GIT_SERVER_URL" >> "$GITHUB_ENV"
        echo "GIT_REPOSITORY=$GIT_REPOSITORY" >> "$GITHUB_ENV"
        echo "GIT_WORKSPACE=$GIT_WORKSPACE" >> "$GITHUB_ENV"
      env:
        GIT_ACTOR: ${{ github.actor }}
        GIT_SERVER_URL: ${{ github.server_url }}
        GIT_REPOSITORY: ${{ github.repository }}
        GIT_WORKSPACE: ${{ github.workspace }}
