networks:
  monitoring:
    driver: bridge

volumes:
  otel_lgtm_data:

services:
  mono-devcon:
    # Build from the Dockerfile and tag the resulting image
    build:
      context: ./devcontainer/
      dockerfile: Dockerfile
    image: mono-devcon:latest

    # Keep the container running indefinitely
    command: sleep infinity

    # Mount the project folder and the rootless Docker socket
    volumes:
      - ..:/workspace
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock

    # Load variables from the specified .env file
    env_file:
      - ./devcontainer/.env
    networks:
      - monitoring

  # ------------------- #
  #      OTel-LGTM      #
  # ------------------- #
  otel-lgtm:
    image: grafana/otel-lgtm:0.11.14
    container_name: otel-lgtm
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - otel_lgtm_data:/data
    networks:
      - monitoring
