receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  # Export traces to Tempo
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Export logs to Loki
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp/v1/logs" # Loki's native OTLP endpoint
    tls:
      insecure: true

  # Export metrics for Prometheus to scrape
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Export profiling data to Pyroscope
  # otlphttp/pyroscope:
  #   endpoint: "http://pyroscope:4318" # <-- Points to Pyroscope's OTLP port
  #   tls:
  #     insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
    # profiles:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlphttp/pyroscope]
