name: Sub Debug Workflow

on:
  workflow_call:

permissions:
  packages: write
  contents: read

concurrency:
  group: debug-workflow
  cancel-in-progress: true

env:
  GH_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MONO_WORK_DIR: ".github/workflows"
  MONO_LOG_LEVEL: debug
  EVENT_BRANCH: debug-workflow

jobs:
  cd:
    name: Debug
    environment: GitHub
    runs-on: ubuntu-22.04
    steps:
      - name: Debug Available Secrets
        run: echo "${{ toJSON(secrets) }}"
      - name: Check if secret is set
        if: ${{ env.AUTH_TOKEN == '' }}
        run: |
          echo "AUTH_TOKEN is empty or not set."
          exit 1
        env:
          AUTH_TOKEN: ${{ secrets.GHA_PAT }}
      - name: CLI Auth
        uses: Duncan3142/mono/actions/gh-cli@main
        with:
          token: ${{ secrets.GHA_PAT }}
