name: Package CD

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      log-level:
        required: false
        type: string
        default: debug
      deployment-ref:
        required: false
        type: string
        default: main

permissions:
  packages: write
  contents: read

concurrency:
  group: "${{ inputs.working-directory }}_CD"
  cancel-in-progress: false

env:
  GH_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MONO_WORK_DIR: ${{ inputs.working-directory }}
  SEMVER_BRANCH_PREFIX: ${{ vars.SEMVER_BRANCH_PREFIX }}
  MONO_LOG_LEVEL: ${{ inputs.log-level }}
  EVENT_BRANCH: ${{ inputs.deployment-ref }}

jobs:
  cd:
    name: CD
    environment: GitHub
    runs-on: ubuntu-22.04
    steps:
      - name: CD
        uses: Duncan3142/mono/actions/npm-pkg-cd@main
        with:
          token: ${{ secrets.GHA_PAT }}
