name: Generic Package CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      pr-branch:
        required: true
        type: string
      pr-meta-json:
        required: true
        type: string
      log-level:
        required: false
        type: string
        default: debug

concurrency:
  group: "${{ inputs.working-directory }}_CI"
  cancel-in-progress: true

env:
  GH_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MONO_WORK_DIR: ${{ inputs.working-directory }}
  MONO_LOG_LEVEL: ${{ inputs.log-level }}
  EVENT_BRANCH: ${{ inputs.pr-branch }}

jobs:
  ci:
    name: CI
    if: ${{ fromJSON(inputs.pr-meta-json).state == 'open' && fromJSON(inputs.pr-meta-json).draft == false }}
    runs-on: ubuntu-22.04
    steps:
      - name: CI
        uses: Duncan3142/mono/actions/npm-ci@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
