name: Prettier Config CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - '.github/workflows/pkgs-prettier-config-ci.yml'
      - 'pkgs/prettier-config/**'
      - '!pkgs/prettier-config/.changeset/*'
      - '!pkgs/prettier-config/CHANGELOG.md'

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

env:
  GH_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MONO_WORK_DIR: ${{ vars.PRETTIER_CONFIG_DIR }}
  MONO_LOG_LEVEL: debug
  EVENT_BRANCH: ${{ github.head_ref }}

jobs:
  ci:
    if: github.event.pull_request.state == 'open' && github.event.pull_request.draft == false
    name: CI
    runs-on: ubuntu-22.04
    steps:

      - name: CI
        uses: Duncan3142/mono/actions/npm-ci@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
