name: Effect CD

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/pkgs.effect.cd.yml"
      - "pkgs/effect/**"

permissions:
  packages: write
  contents: read

jobs:
  cd:
    name: Effect CD
    uses: ./.github/workflows/generic.pkgs.cd.yml
    secrets: inherit
    with:
      working-directory: ${{ vars.EFFECT_DIR }}
