name: ESLint Config CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - ".github/workflows/pkgs.eslint-config.ci.yml"
      - "pkgs/eslint-config/**"
      - "!pkgs/eslint-config/.changeset/*"
      - "!pkgs/eslint-config/CHANGELOG.md"

jobs:
  ci:
    if: github.event.pull_request.state == 'open' && github.event.pull_request.draft == false
    name: ESLint Config CI
    uses: ./.github/workflows/generic.pkgs.ci.yml
    with:
      working-directory: ${{ vars.ESLINT_CONFIG_DIR }}
      pr-branch: ${{ github.head_ref }}
